/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BlackManSpecApplyConfiguration represents an declarative configuration of the BlackManSpec type for use
// with apply.
type BlackManSpecApplyConfiguration struct {
	Name    *string `json:"name,omitempty"`
	Region  *string `json:"region,omitempty"`
	Version *string `json:"version,omitempty"`
}

// BlackManSpecApplyConfiguration constructs an declarative configuration of the BlackManSpec type for use with
// apply.
func BlackManSpec() *BlackManSpecApplyConfiguration {
	return &BlackManSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BlackManSpecApplyConfiguration) WithName(value string) *BlackManSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *BlackManSpecApplyConfiguration) WithRegion(value string) *BlackManSpecApplyConfiguration {
	b.Region = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *BlackManSpecApplyConfiguration) WithVersion(value string) *BlackManSpecApplyConfiguration {
	b.Version = &value
	return b
}
