/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/sheikh-arman/test-crd-controller/pkg/apis/arman.com/v1alpha1"
	armancomv1alpha1 "github.com/sheikh-arman/test-crd-controller/pkg/client/applyconfiguration/arman.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBlackMans implements BlackManInterface
type FakeBlackMans struct {
	Fake *FakeArmanV1alpha1
	ns   string
}

var blackmansResource = v1alpha1.SchemeGroupVersion.WithResource("blackmans")

var blackmansKind = v1alpha1.SchemeGroupVersion.WithKind("BlackMan")

// Get takes name of the blackMan, and returns the corresponding blackMan object, and an error if there is any.
func (c *FakeBlackMans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BlackMan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(blackmansResource, c.ns, name), &v1alpha1.BlackMan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlackMan), err
}

// List takes label and field selectors, and returns the list of BlackMans that match those selectors.
func (c *FakeBlackMans) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BlackManList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(blackmansResource, blackmansKind, c.ns, opts), &v1alpha1.BlackManList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BlackManList{ListMeta: obj.(*v1alpha1.BlackManList).ListMeta}
	for _, item := range obj.(*v1alpha1.BlackManList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested blackMans.
func (c *FakeBlackMans) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(blackmansResource, c.ns, opts))

}

// Create takes the representation of a blackMan and creates it.  Returns the server's representation of the blackMan, and an error, if there is any.
func (c *FakeBlackMans) Create(ctx context.Context, blackMan *v1alpha1.BlackMan, opts v1.CreateOptions) (result *v1alpha1.BlackMan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(blackmansResource, c.ns, blackMan), &v1alpha1.BlackMan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlackMan), err
}

// Update takes the representation of a blackMan and updates it. Returns the server's representation of the blackMan, and an error, if there is any.
func (c *FakeBlackMans) Update(ctx context.Context, blackMan *v1alpha1.BlackMan, opts v1.UpdateOptions) (result *v1alpha1.BlackMan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(blackmansResource, c.ns, blackMan), &v1alpha1.BlackMan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlackMan), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBlackMans) UpdateStatus(ctx context.Context, blackMan *v1alpha1.BlackMan, opts v1.UpdateOptions) (*v1alpha1.BlackMan, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(blackmansResource, "status", c.ns, blackMan), &v1alpha1.BlackMan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlackMan), err
}

// Delete takes name of the blackMan and deletes it. Returns an error if one occurs.
func (c *FakeBlackMans) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(blackmansResource, c.ns, name, opts), &v1alpha1.BlackMan{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBlackMans) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(blackmansResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BlackManList{})
	return err
}

// Patch applies the patch and returns the patched blackMan.
func (c *FakeBlackMans) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BlackMan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(blackmansResource, c.ns, name, pt, data, subresources...), &v1alpha1.BlackMan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlackMan), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied blackMan.
func (c *FakeBlackMans) Apply(ctx context.Context, blackMan *armancomv1alpha1.BlackManApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.BlackMan, err error) {
	if blackMan == nil {
		return nil, fmt.Errorf("blackMan provided to Apply must not be nil")
	}
	data, err := json.Marshal(blackMan)
	if err != nil {
		return nil, err
	}
	name := blackMan.Name
	if name == nil {
		return nil, fmt.Errorf("blackMan.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(blackmansResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.BlackMan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlackMan), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeBlackMans) ApplyStatus(ctx context.Context, blackMan *armancomv1alpha1.BlackManApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.BlackMan, err error) {
	if blackMan == nil {
		return nil, fmt.Errorf("blackMan provided to Apply must not be nil")
	}
	data, err := json.Marshal(blackMan)
	if err != nil {
		return nil, err
	}
	name := blackMan.Name
	if name == nil {
		return nil, fmt.Errorf("blackMan.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(blackmansResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.BlackMan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlackMan), err
}
